[package]
name = "roster"
version = "0.1.0"
authors = ["Jeffrey Lym <jeffreyalym@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-postgres = "0.6.0"
tokio = { version = "0.3", features = ["full"] }
